imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

parameters:
    database_host: %graviton_vcap.naseskoly_admin_db.host%
    database_port: %graviton_vcap.naseskoly_admin_db.port%
    database_name: %graviton_vcap.naseskoly_admin_db.db%
    database_user: %graviton_vcap.naseskoly_admin_db.username%
    database_password: %graviton_vcap.naseskoly_admin_db.password%

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
