# This file is a "template" of what your parameters.yml file should look like
# Set parameters here that may be different on each deployment target of the app, e.g. development, staging, production.
# http://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration
parameters:
    database_host:     localhost
    database_port:
    database_name:     mojeskoly
    database_user:     mojeskoly
    database_password: 0SwgFPHHyg7qkeg5


    # if we ever use Bluemix
    #database_host:     %graviton_vcap.credentials.hostname%
    #database_port:     %graviton_vcap.credentials.port%
    #database_name:     %graviton_vcap.credentials.name%
    #database_user:     %graviton_vcap.credentials.username%
    #database_password: %graviton_vcap.credentials.password%

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            LoremIpsum
