app:
    resource: "@AppBundle/Controller/"
    type:     annotation

transformator:
    resource: "@TransformatorBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"