# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    transformator.token: "ece59a72-9637-4205-80de-fb2b5d39a275"

    data.msmt: "http://stistko.uiv.cz/rejstrik/rejstrik_151103.zip"



services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.listener.registration:
        class: AppBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    transformator.listener.token_listener:
        class: TransformatorBundle\EventListener\TokenListener
        arguments: ["%transformator.token%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    transformator.utils.file_operations:
        class: TransformatorBundle\Utils\FileOperations
        arguments: ["%data.msmt%"]