# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    transformator.token: "ece59a72-9637-4205-80de-fb2b5d39a275"
    data.msmt: "http://stistko.uiv.cz/rejstrik/rejstrik_151103.zip"

    # elastic credentials
    elastic.address: "http://127.0.0.1:9200"
    elastic.index: "mojeskoly"
    elastic.type: "school"

    # Google Maps API
    googleMaps.key: "AIzaSyB0_V71MYMxE-uatgqNMBqANs5ZT8uH2FI"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.listener.registration:
        class: AppBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    transformator.listener.token_listener:
        class: TransformatorBundle\EventListener\TokenListener
        arguments: ["%transformator.token%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    transformator.utils.msmt_parser:
        class: TransformatorBundle\Utils\MsmtParser
        arguments: ["@security.token_storage", "@doctrine.orm.entity_manager", "@transformator.utils.dumping_service", "%data.msmt%"]
    transformator.utils.csi_parser:
        class: TransformatorBundle\Utils\CsiParser
        arguments: ["@security.token_storage", "@doctrine.orm.entity_manager", "@transformator.utils.dumping_service"]

    transformator.utils.dumping_service:
        class: TransformatorBundle\Utils\DumpingService
        arguments: ["@session"]

    transformator.utils.build:
        class: TransformatorBundle\Utils\Build
        arguments: ["@security.token_storage", "@doctrine.orm.entity_manager", "@transformator.utils.geolocation", "@transformator.utils.dumping_service", "%elastic.address%", "%elastic.index%", "%elastic.type%"]

    transformator.utils.geolocation:
        class: TransformatorBundle\Utils\Geolocation
        arguments: ["@ci.restclient", "@transformator.utils.dumping_service", "%googleMaps.key%"]